version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3

executors:
  python:
    docker:
      - image: cimg/python:3.14
  renovate:
    docker:
      - image: renovate/renovate:latest

jobs:
  setup-workspace:
    executor: python
    steps:
      - checkout
      - run: uv sync
      - persist_to_workspace:
          root: .
          paths:
            - .
            - .venv
  run-lint:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run: uv run pylint src/
  upload-coverage:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run: |
          uv run pytest tests/ --cov
          uv run coverage xml
      - codecov/upload
  activate-renovatebot:
    executor: renovate
    steps:
      - run: renovate

workflows:
  code-analysis:
    jobs:
      - setup-workspace
      - run-lint:
          requires: [setup-workspace]
      - upload-coverage:
          requires: [setup-workspace]
      - activate-renovatebot
