name: Setup Workspace
description: Checkout and install all dependencies

runs:
  using: composite
  steps:
  - uses: astral-sh/setup-uv@v8.1.0
    with:
      python-version: 3.14
      enable-cache: true

  - shell: bash
    run: uv sync --locked
