version: 2.1

orbs:
  codecov: codecov/codecov@3

executors:
  linux:
    docker:
      - image: cimg/python:3.12

jobs:
  upload-coverage:
    executor: linux
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest --cov .
      - codecov/upload

workflows:
  build:
    jobs:
      - upload-coverage
