version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest --cov .
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
